/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as VendorsRouteImport } from "./routes/vendors";
import { Route as OnboardingRouteImport } from "./routes/onboarding";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as TeamsIndexRouteImport } from "./routes/teams/index";
import { Route as TeamsNewRouteImport } from "./routes/teams/new";
import { Route as TeamsJoinRouteImport } from "./routes/teams/join";
import { Route as TeamProgramNumberRouteImport } from "./routes/team/$program/$number";
import { Route as TeamProgramNumberIndexRouteImport } from "./routes/team/$program/$number/index";
import { Route as TeamProgramNumberVendorsIndexRouteImport } from "./routes/team/$program/$number/vendors/index";
import { Route as TeamProgramNumberSponsorsIndexRouteImport } from "./routes/team/$program/$number/sponsors/index";
import { Route as TeamProgramNumberSoftwareIndexRouteImport } from "./routes/team/$program/$number/software/index";
import { Route as TeamProgramNumberSettingsIndexRouteImport } from "./routes/team/$program/$number/settings/index";
import { Route as TeamProgramNumberRobotsIndexRouteImport } from "./routes/team/$program/$number/robots/index";
import { Route as TeamProgramNumberPartsIndexRouteImport } from "./routes/team/$program/$number/parts/index";
import { Route as TeamProgramNumberOutreachIndexRouteImport } from "./routes/team/$program/$number/outreach/index";
import { Route as TeamProgramNumberOrdersIndexRouteImport } from "./routes/team/$program/$number/orders/index";
import { Route as TeamProgramNumberOperationsIndexRouteImport } from "./routes/team/$program/$number/operations/index";
import { Route as TeamProgramNumberMembersIndexRouteImport } from "./routes/team/$program/$number/members/index";
import { Route as TeamProgramNumberMarketingIndexRouteImport } from "./routes/team/$program/$number/marketing/index";
import { Route as TeamProgramNumberFinanceIndexRouteImport } from "./routes/team/$program/$number/finance/index";
import { Route as TeamProgramNumberFabricationIndexRouteImport } from "./routes/team/$program/$number/fabrication/index";
import { Route as TeamProgramNumberCalendarIndexRouteImport } from "./routes/team/$program/$number/calendar/index";
import { Route as TeamProgramNumberSettingsSeasonsRouteImport } from "./routes/team/$program/$number/settings/seasons";
import { Route as TeamProgramNumberVendorsVendorIdIndexRouteImport } from "./routes/team/$program/$number/vendors/$vendorId/index";
import { Route as TeamProgramNumberRobotsNewIndexRouteImport } from "./routes/team/$program/$number/robots/new/index";
import { Route as TeamProgramNumberRobotsRobotIdIndexRouteImport } from "./routes/team/$program/$number/robots/$robotId/index";
import { Route as TeamProgramNumberPartsNewIndexRouteImport } from "./routes/team/$program/$number/parts/new/index";
import { Route as TeamProgramNumberPartsPartIdIndexRouteImport } from "./routes/team/$program/$number/parts/$partId/index";
import { Route as TeamProgramNumberOrdersNewIndexRouteImport } from "./routes/team/$program/$number/orders/new/index";
import { Route as TeamProgramNumberOrdersOrderIdIndexRouteImport } from "./routes/team/$program/$number/orders/$orderId/index";
import { Route as TeamProgramNumberRobotsRobotIdBomIndexRouteImport } from "./routes/team/$program/$number/robots/$robotId/bom/index";
import { Route as TeamProgramNumberPartsPartIdEditIndexRouteImport } from "./routes/team/$program/$number/parts/$partId/edit/index";
import { Route as TeamProgramNumberRobotsRobotIdBomNewIndexRouteImport } from "./routes/team/$program/$number/robots/$robotId/bom/new/index";

const VendorsRoute = VendorsRouteImport.update({
  id: "/vendors",
  path: "/vendors",
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingRoute = OnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: "/teams/",
  path: "/teams/",
  getParentRoute: () => rootRouteImport,
} as any);
const TeamsNewRoute = TeamsNewRouteImport.update({
  id: "/teams/new",
  path: "/teams/new",
  getParentRoute: () => rootRouteImport,
} as any);
const TeamsJoinRoute = TeamsJoinRouteImport.update({
  id: "/teams/join",
  path: "/teams/join",
  getParentRoute: () => rootRouteImport,
} as any);
const TeamProgramNumberRoute = TeamProgramNumberRouteImport.update({
  id: "/team/$program/$number",
  path: "/team/$program/$number",
  getParentRoute: () => rootRouteImport,
} as any);
const TeamProgramNumberIndexRoute = TeamProgramNumberIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => TeamProgramNumberRoute,
} as any);
const TeamProgramNumberVendorsIndexRoute =
  TeamProgramNumberVendorsIndexRouteImport.update({
    id: "/vendors/",
    path: "/vendors/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberSponsorsIndexRoute =
  TeamProgramNumberSponsorsIndexRouteImport.update({
    id: "/sponsors/",
    path: "/sponsors/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberSoftwareIndexRoute =
  TeamProgramNumberSoftwareIndexRouteImport.update({
    id: "/software/",
    path: "/software/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberSettingsIndexRoute =
  TeamProgramNumberSettingsIndexRouteImport.update({
    id: "/settings/",
    path: "/settings/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberRobotsIndexRoute =
  TeamProgramNumberRobotsIndexRouteImport.update({
    id: "/robots/",
    path: "/robots/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberPartsIndexRoute =
  TeamProgramNumberPartsIndexRouteImport.update({
    id: "/parts/",
    path: "/parts/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberOutreachIndexRoute =
  TeamProgramNumberOutreachIndexRouteImport.update({
    id: "/outreach/",
    path: "/outreach/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberOrdersIndexRoute =
  TeamProgramNumberOrdersIndexRouteImport.update({
    id: "/orders/",
    path: "/orders/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberOperationsIndexRoute =
  TeamProgramNumberOperationsIndexRouteImport.update({
    id: "/operations/",
    path: "/operations/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberMembersIndexRoute =
  TeamProgramNumberMembersIndexRouteImport.update({
    id: "/members/",
    path: "/members/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberMarketingIndexRoute =
  TeamProgramNumberMarketingIndexRouteImport.update({
    id: "/marketing/",
    path: "/marketing/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberFinanceIndexRoute =
  TeamProgramNumberFinanceIndexRouteImport.update({
    id: "/finance/",
    path: "/finance/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberFabricationIndexRoute =
  TeamProgramNumberFabricationIndexRouteImport.update({
    id: "/fabrication/",
    path: "/fabrication/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberCalendarIndexRoute =
  TeamProgramNumberCalendarIndexRouteImport.update({
    id: "/calendar/",
    path: "/calendar/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberSettingsSeasonsRoute =
  TeamProgramNumberSettingsSeasonsRouteImport.update({
    id: "/settings/seasons",
    path: "/settings/seasons",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberVendorsVendorIdIndexRoute =
  TeamProgramNumberVendorsVendorIdIndexRouteImport.update({
    id: "/vendors/$vendorId/",
    path: "/vendors/$vendorId/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberRobotsNewIndexRoute =
  TeamProgramNumberRobotsNewIndexRouteImport.update({
    id: "/robots/new/",
    path: "/robots/new/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberRobotsRobotIdIndexRoute =
  TeamProgramNumberRobotsRobotIdIndexRouteImport.update({
    id: "/robots/$robotId/",
    path: "/robots/$robotId/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberPartsNewIndexRoute =
  TeamProgramNumberPartsNewIndexRouteImport.update({
    id: "/parts/new/",
    path: "/parts/new/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberPartsPartIdIndexRoute =
  TeamProgramNumberPartsPartIdIndexRouteImport.update({
    id: "/parts/$partId/",
    path: "/parts/$partId/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberOrdersNewIndexRoute =
  TeamProgramNumberOrdersNewIndexRouteImport.update({
    id: "/orders/new/",
    path: "/orders/new/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberOrdersOrderIdIndexRoute =
  TeamProgramNumberOrdersOrderIdIndexRouteImport.update({
    id: "/orders/$orderId/",
    path: "/orders/$orderId/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberRobotsRobotIdBomIndexRoute =
  TeamProgramNumberRobotsRobotIdBomIndexRouteImport.update({
    id: "/robots/$robotId/bom/",
    path: "/robots/$robotId/bom/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberPartsPartIdEditIndexRoute =
  TeamProgramNumberPartsPartIdEditIndexRouteImport.update({
    id: "/parts/$partId/edit/",
    path: "/parts/$partId/edit/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);
const TeamProgramNumberRobotsRobotIdBomNewIndexRoute =
  TeamProgramNumberRobotsRobotIdBomNewIndexRouteImport.update({
    id: "/robots/$robotId/bom/new/",
    path: "/robots/$robotId/bom/new/",
    getParentRoute: () => TeamProgramNumberRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/onboarding": typeof OnboardingRoute;
  "/vendors": typeof VendorsRoute;
  "/teams/join": typeof TeamsJoinRoute;
  "/teams/new": typeof TeamsNewRoute;
  "/teams": typeof TeamsIndexRoute;
  "/team/$program/$number": typeof TeamProgramNumberRouteWithChildren;
  "/team/$program/$number/": typeof TeamProgramNumberIndexRoute;
  "/team/$program/$number/settings/seasons": typeof TeamProgramNumberSettingsSeasonsRoute;
  "/team/$program/$number/calendar": typeof TeamProgramNumberCalendarIndexRoute;
  "/team/$program/$number/fabrication": typeof TeamProgramNumberFabricationIndexRoute;
  "/team/$program/$number/finance": typeof TeamProgramNumberFinanceIndexRoute;
  "/team/$program/$number/marketing": typeof TeamProgramNumberMarketingIndexRoute;
  "/team/$program/$number/members": typeof TeamProgramNumberMembersIndexRoute;
  "/team/$program/$number/operations": typeof TeamProgramNumberOperationsIndexRoute;
  "/team/$program/$number/orders": typeof TeamProgramNumberOrdersIndexRoute;
  "/team/$program/$number/outreach": typeof TeamProgramNumberOutreachIndexRoute;
  "/team/$program/$number/parts": typeof TeamProgramNumberPartsIndexRoute;
  "/team/$program/$number/robots": typeof TeamProgramNumberRobotsIndexRoute;
  "/team/$program/$number/settings": typeof TeamProgramNumberSettingsIndexRoute;
  "/team/$program/$number/software": typeof TeamProgramNumberSoftwareIndexRoute;
  "/team/$program/$number/sponsors": typeof TeamProgramNumberSponsorsIndexRoute;
  "/team/$program/$number/vendors": typeof TeamProgramNumberVendorsIndexRoute;
  "/team/$program/$number/orders/$orderId": typeof TeamProgramNumberOrdersOrderIdIndexRoute;
  "/team/$program/$number/orders/new": typeof TeamProgramNumberOrdersNewIndexRoute;
  "/team/$program/$number/parts/$partId": typeof TeamProgramNumberPartsPartIdIndexRoute;
  "/team/$program/$number/parts/new": typeof TeamProgramNumberPartsNewIndexRoute;
  "/team/$program/$number/robots/$robotId": typeof TeamProgramNumberRobotsRobotIdIndexRoute;
  "/team/$program/$number/robots/new": typeof TeamProgramNumberRobotsNewIndexRoute;
  "/team/$program/$number/vendors/$vendorId": typeof TeamProgramNumberVendorsVendorIdIndexRoute;
  "/team/$program/$number/parts/$partId/edit": typeof TeamProgramNumberPartsPartIdEditIndexRoute;
  "/team/$program/$number/robots/$robotId/bom": typeof TeamProgramNumberRobotsRobotIdBomIndexRoute;
  "/team/$program/$number/robots/$robotId/bom/new": typeof TeamProgramNumberRobotsRobotIdBomNewIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/onboarding": typeof OnboardingRoute;
  "/vendors": typeof VendorsRoute;
  "/teams/join": typeof TeamsJoinRoute;
  "/teams/new": typeof TeamsNewRoute;
  "/teams": typeof TeamsIndexRoute;
  "/team/$program/$number": typeof TeamProgramNumberIndexRoute;
  "/team/$program/$number/settings/seasons": typeof TeamProgramNumberSettingsSeasonsRoute;
  "/team/$program/$number/calendar": typeof TeamProgramNumberCalendarIndexRoute;
  "/team/$program/$number/fabrication": typeof TeamProgramNumberFabricationIndexRoute;
  "/team/$program/$number/finance": typeof TeamProgramNumberFinanceIndexRoute;
  "/team/$program/$number/marketing": typeof TeamProgramNumberMarketingIndexRoute;
  "/team/$program/$number/members": typeof TeamProgramNumberMembersIndexRoute;
  "/team/$program/$number/operations": typeof TeamProgramNumberOperationsIndexRoute;
  "/team/$program/$number/orders": typeof TeamProgramNumberOrdersIndexRoute;
  "/team/$program/$number/outreach": typeof TeamProgramNumberOutreachIndexRoute;
  "/team/$program/$number/parts": typeof TeamProgramNumberPartsIndexRoute;
  "/team/$program/$number/robots": typeof TeamProgramNumberRobotsIndexRoute;
  "/team/$program/$number/settings": typeof TeamProgramNumberSettingsIndexRoute;
  "/team/$program/$number/software": typeof TeamProgramNumberSoftwareIndexRoute;
  "/team/$program/$number/sponsors": typeof TeamProgramNumberSponsorsIndexRoute;
  "/team/$program/$number/vendors": typeof TeamProgramNumberVendorsIndexRoute;
  "/team/$program/$number/orders/$orderId": typeof TeamProgramNumberOrdersOrderIdIndexRoute;
  "/team/$program/$number/orders/new": typeof TeamProgramNumberOrdersNewIndexRoute;
  "/team/$program/$number/parts/$partId": typeof TeamProgramNumberPartsPartIdIndexRoute;
  "/team/$program/$number/parts/new": typeof TeamProgramNumberPartsNewIndexRoute;
  "/team/$program/$number/robots/$robotId": typeof TeamProgramNumberRobotsRobotIdIndexRoute;
  "/team/$program/$number/robots/new": typeof TeamProgramNumberRobotsNewIndexRoute;
  "/team/$program/$number/vendors/$vendorId": typeof TeamProgramNumberVendorsVendorIdIndexRoute;
  "/team/$program/$number/parts/$partId/edit": typeof TeamProgramNumberPartsPartIdEditIndexRoute;
  "/team/$program/$number/robots/$robotId/bom": typeof TeamProgramNumberRobotsRobotIdBomIndexRoute;
  "/team/$program/$number/robots/$robotId/bom/new": typeof TeamProgramNumberRobotsRobotIdBomNewIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/onboarding": typeof OnboardingRoute;
  "/vendors": typeof VendorsRoute;
  "/teams/join": typeof TeamsJoinRoute;
  "/teams/new": typeof TeamsNewRoute;
  "/teams/": typeof TeamsIndexRoute;
  "/team/$program/$number": typeof TeamProgramNumberRouteWithChildren;
  "/team/$program/$number/": typeof TeamProgramNumberIndexRoute;
  "/team/$program/$number/settings/seasons": typeof TeamProgramNumberSettingsSeasonsRoute;
  "/team/$program/$number/calendar/": typeof TeamProgramNumberCalendarIndexRoute;
  "/team/$program/$number/fabrication/": typeof TeamProgramNumberFabricationIndexRoute;
  "/team/$program/$number/finance/": typeof TeamProgramNumberFinanceIndexRoute;
  "/team/$program/$number/marketing/": typeof TeamProgramNumberMarketingIndexRoute;
  "/team/$program/$number/members/": typeof TeamProgramNumberMembersIndexRoute;
  "/team/$program/$number/operations/": typeof TeamProgramNumberOperationsIndexRoute;
  "/team/$program/$number/orders/": typeof TeamProgramNumberOrdersIndexRoute;
  "/team/$program/$number/outreach/": typeof TeamProgramNumberOutreachIndexRoute;
  "/team/$program/$number/parts/": typeof TeamProgramNumberPartsIndexRoute;
  "/team/$program/$number/robots/": typeof TeamProgramNumberRobotsIndexRoute;
  "/team/$program/$number/settings/": typeof TeamProgramNumberSettingsIndexRoute;
  "/team/$program/$number/software/": typeof TeamProgramNumberSoftwareIndexRoute;
  "/team/$program/$number/sponsors/": typeof TeamProgramNumberSponsorsIndexRoute;
  "/team/$program/$number/vendors/": typeof TeamProgramNumberVendorsIndexRoute;
  "/team/$program/$number/orders/$orderId/": typeof TeamProgramNumberOrdersOrderIdIndexRoute;
  "/team/$program/$number/orders/new/": typeof TeamProgramNumberOrdersNewIndexRoute;
  "/team/$program/$number/parts/$partId/": typeof TeamProgramNumberPartsPartIdIndexRoute;
  "/team/$program/$number/parts/new/": typeof TeamProgramNumberPartsNewIndexRoute;
  "/team/$program/$number/robots/$robotId/": typeof TeamProgramNumberRobotsRobotIdIndexRoute;
  "/team/$program/$number/robots/new/": typeof TeamProgramNumberRobotsNewIndexRoute;
  "/team/$program/$number/vendors/$vendorId/": typeof TeamProgramNumberVendorsVendorIdIndexRoute;
  "/team/$program/$number/parts/$partId/edit/": typeof TeamProgramNumberPartsPartIdEditIndexRoute;
  "/team/$program/$number/robots/$robotId/bom/": typeof TeamProgramNumberRobotsRobotIdBomIndexRoute;
  "/team/$program/$number/robots/$robotId/bom/new/": typeof TeamProgramNumberRobotsRobotIdBomNewIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/login"
    | "/onboarding"
    | "/vendors"
    | "/teams/join"
    | "/teams/new"
    | "/teams"
    | "/team/$program/$number"
    | "/team/$program/$number/"
    | "/team/$program/$number/settings/seasons"
    | "/team/$program/$number/calendar"
    | "/team/$program/$number/fabrication"
    | "/team/$program/$number/finance"
    | "/team/$program/$number/marketing"
    | "/team/$program/$number/members"
    | "/team/$program/$number/operations"
    | "/team/$program/$number/orders"
    | "/team/$program/$number/outreach"
    | "/team/$program/$number/parts"
    | "/team/$program/$number/robots"
    | "/team/$program/$number/settings"
    | "/team/$program/$number/software"
    | "/team/$program/$number/sponsors"
    | "/team/$program/$number/vendors"
    | "/team/$program/$number/orders/$orderId"
    | "/team/$program/$number/orders/new"
    | "/team/$program/$number/parts/$partId"
    | "/team/$program/$number/parts/new"
    | "/team/$program/$number/robots/$robotId"
    | "/team/$program/$number/robots/new"
    | "/team/$program/$number/vendors/$vendorId"
    | "/team/$program/$number/parts/$partId/edit"
    | "/team/$program/$number/robots/$robotId/bom"
    | "/team/$program/$number/robots/$robotId/bom/new";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/dashboard"
    | "/login"
    | "/onboarding"
    | "/vendors"
    | "/teams/join"
    | "/teams/new"
    | "/teams"
    | "/team/$program/$number"
    | "/team/$program/$number/settings/seasons"
    | "/team/$program/$number/calendar"
    | "/team/$program/$number/fabrication"
    | "/team/$program/$number/finance"
    | "/team/$program/$number/marketing"
    | "/team/$program/$number/members"
    | "/team/$program/$number/operations"
    | "/team/$program/$number/orders"
    | "/team/$program/$number/outreach"
    | "/team/$program/$number/parts"
    | "/team/$program/$number/robots"
    | "/team/$program/$number/settings"
    | "/team/$program/$number/software"
    | "/team/$program/$number/sponsors"
    | "/team/$program/$number/vendors"
    | "/team/$program/$number/orders/$orderId"
    | "/team/$program/$number/orders/new"
    | "/team/$program/$number/parts/$partId"
    | "/team/$program/$number/parts/new"
    | "/team/$program/$number/robots/$robotId"
    | "/team/$program/$number/robots/new"
    | "/team/$program/$number/vendors/$vendorId"
    | "/team/$program/$number/parts/$partId/edit"
    | "/team/$program/$number/robots/$robotId/bom"
    | "/team/$program/$number/robots/$robotId/bom/new";
  id:
    | "__root__"
    | "/"
    | "/dashboard"
    | "/login"
    | "/onboarding"
    | "/vendors"
    | "/teams/join"
    | "/teams/new"
    | "/teams/"
    | "/team/$program/$number"
    | "/team/$program/$number/"
    | "/team/$program/$number/settings/seasons"
    | "/team/$program/$number/calendar/"
    | "/team/$program/$number/fabrication/"
    | "/team/$program/$number/finance/"
    | "/team/$program/$number/marketing/"
    | "/team/$program/$number/members/"
    | "/team/$program/$number/operations/"
    | "/team/$program/$number/orders/"
    | "/team/$program/$number/outreach/"
    | "/team/$program/$number/parts/"
    | "/team/$program/$number/robots/"
    | "/team/$program/$number/settings/"
    | "/team/$program/$number/software/"
    | "/team/$program/$number/sponsors/"
    | "/team/$program/$number/vendors/"
    | "/team/$program/$number/orders/$orderId/"
    | "/team/$program/$number/orders/new/"
    | "/team/$program/$number/parts/$partId/"
    | "/team/$program/$number/parts/new/"
    | "/team/$program/$number/robots/$robotId/"
    | "/team/$program/$number/robots/new/"
    | "/team/$program/$number/vendors/$vendorId/"
    | "/team/$program/$number/parts/$partId/edit/"
    | "/team/$program/$number/robots/$robotId/bom/"
    | "/team/$program/$number/robots/$robotId/bom/new/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRoute: typeof DashboardRoute;
  LoginRoute: typeof LoginRoute;
  OnboardingRoute: typeof OnboardingRoute;
  VendorsRoute: typeof VendorsRoute;
  TeamsJoinRoute: typeof TeamsJoinRoute;
  TeamsNewRoute: typeof TeamsNewRoute;
  TeamsIndexRoute: typeof TeamsIndexRoute;
  TeamProgramNumberRoute: typeof TeamProgramNumberRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/vendors": {
      id: "/vendors";
      path: "/vendors";
      fullPath: "/vendors";
      preLoaderRoute: typeof VendorsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/onboarding": {
      id: "/onboarding";
      path: "/onboarding";
      fullPath: "/onboarding";
      preLoaderRoute: typeof OnboardingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/teams/": {
      id: "/teams/";
      path: "/teams";
      fullPath: "/teams";
      preLoaderRoute: typeof TeamsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/teams/new": {
      id: "/teams/new";
      path: "/teams/new";
      fullPath: "/teams/new";
      preLoaderRoute: typeof TeamsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/teams/join": {
      id: "/teams/join";
      path: "/teams/join";
      fullPath: "/teams/join";
      preLoaderRoute: typeof TeamsJoinRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/team/$program/$number": {
      id: "/team/$program/$number";
      path: "/team/$program/$number";
      fullPath: "/team/$program/$number";
      preLoaderRoute: typeof TeamProgramNumberRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/team/$program/$number/": {
      id: "/team/$program/$number/";
      path: "/";
      fullPath: "/team/$program/$number/";
      preLoaderRoute: typeof TeamProgramNumberIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/vendors/": {
      id: "/team/$program/$number/vendors/";
      path: "/vendors";
      fullPath: "/team/$program/$number/vendors";
      preLoaderRoute: typeof TeamProgramNumberVendorsIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/sponsors/": {
      id: "/team/$program/$number/sponsors/";
      path: "/sponsors";
      fullPath: "/team/$program/$number/sponsors";
      preLoaderRoute: typeof TeamProgramNumberSponsorsIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/software/": {
      id: "/team/$program/$number/software/";
      path: "/software";
      fullPath: "/team/$program/$number/software";
      preLoaderRoute: typeof TeamProgramNumberSoftwareIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/settings/": {
      id: "/team/$program/$number/settings/";
      path: "/settings";
      fullPath: "/team/$program/$number/settings";
      preLoaderRoute: typeof TeamProgramNumberSettingsIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/robots/": {
      id: "/team/$program/$number/robots/";
      path: "/robots";
      fullPath: "/team/$program/$number/robots";
      preLoaderRoute: typeof TeamProgramNumberRobotsIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/parts/": {
      id: "/team/$program/$number/parts/";
      path: "/parts";
      fullPath: "/team/$program/$number/parts";
      preLoaderRoute: typeof TeamProgramNumberPartsIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/outreach/": {
      id: "/team/$program/$number/outreach/";
      path: "/outreach";
      fullPath: "/team/$program/$number/outreach";
      preLoaderRoute: typeof TeamProgramNumberOutreachIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/orders/": {
      id: "/team/$program/$number/orders/";
      path: "/orders";
      fullPath: "/team/$program/$number/orders";
      preLoaderRoute: typeof TeamProgramNumberOrdersIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/operations/": {
      id: "/team/$program/$number/operations/";
      path: "/operations";
      fullPath: "/team/$program/$number/operations";
      preLoaderRoute: typeof TeamProgramNumberOperationsIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/members/": {
      id: "/team/$program/$number/members/";
      path: "/members";
      fullPath: "/team/$program/$number/members";
      preLoaderRoute: typeof TeamProgramNumberMembersIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/marketing/": {
      id: "/team/$program/$number/marketing/";
      path: "/marketing";
      fullPath: "/team/$program/$number/marketing";
      preLoaderRoute: typeof TeamProgramNumberMarketingIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/finance/": {
      id: "/team/$program/$number/finance/";
      path: "/finance";
      fullPath: "/team/$program/$number/finance";
      preLoaderRoute: typeof TeamProgramNumberFinanceIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/fabrication/": {
      id: "/team/$program/$number/fabrication/";
      path: "/fabrication";
      fullPath: "/team/$program/$number/fabrication";
      preLoaderRoute: typeof TeamProgramNumberFabricationIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/calendar/": {
      id: "/team/$program/$number/calendar/";
      path: "/calendar";
      fullPath: "/team/$program/$number/calendar";
      preLoaderRoute: typeof TeamProgramNumberCalendarIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/settings/seasons": {
      id: "/team/$program/$number/settings/seasons";
      path: "/settings/seasons";
      fullPath: "/team/$program/$number/settings/seasons";
      preLoaderRoute: typeof TeamProgramNumberSettingsSeasonsRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/vendors/$vendorId/": {
      id: "/team/$program/$number/vendors/$vendorId/";
      path: "/vendors/$vendorId";
      fullPath: "/team/$program/$number/vendors/$vendorId";
      preLoaderRoute: typeof TeamProgramNumberVendorsVendorIdIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/robots/new/": {
      id: "/team/$program/$number/robots/new/";
      path: "/robots/new";
      fullPath: "/team/$program/$number/robots/new";
      preLoaderRoute: typeof TeamProgramNumberRobotsNewIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/robots/$robotId/": {
      id: "/team/$program/$number/robots/$robotId/";
      path: "/robots/$robotId";
      fullPath: "/team/$program/$number/robots/$robotId";
      preLoaderRoute: typeof TeamProgramNumberRobotsRobotIdIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/parts/new/": {
      id: "/team/$program/$number/parts/new/";
      path: "/parts/new";
      fullPath: "/team/$program/$number/parts/new";
      preLoaderRoute: typeof TeamProgramNumberPartsNewIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/parts/$partId/": {
      id: "/team/$program/$number/parts/$partId/";
      path: "/parts/$partId";
      fullPath: "/team/$program/$number/parts/$partId";
      preLoaderRoute: typeof TeamProgramNumberPartsPartIdIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/orders/new/": {
      id: "/team/$program/$number/orders/new/";
      path: "/orders/new";
      fullPath: "/team/$program/$number/orders/new";
      preLoaderRoute: typeof TeamProgramNumberOrdersNewIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/orders/$orderId/": {
      id: "/team/$program/$number/orders/$orderId/";
      path: "/orders/$orderId";
      fullPath: "/team/$program/$number/orders/$orderId";
      preLoaderRoute: typeof TeamProgramNumberOrdersOrderIdIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/robots/$robotId/bom/": {
      id: "/team/$program/$number/robots/$robotId/bom/";
      path: "/robots/$robotId/bom";
      fullPath: "/team/$program/$number/robots/$robotId/bom";
      preLoaderRoute: typeof TeamProgramNumberRobotsRobotIdBomIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/parts/$partId/edit/": {
      id: "/team/$program/$number/parts/$partId/edit/";
      path: "/parts/$partId/edit";
      fullPath: "/team/$program/$number/parts/$partId/edit";
      preLoaderRoute: typeof TeamProgramNumberPartsPartIdEditIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
    "/team/$program/$number/robots/$robotId/bom/new/": {
      id: "/team/$program/$number/robots/$robotId/bom/new/";
      path: "/robots/$robotId/bom/new";
      fullPath: "/team/$program/$number/robots/$robotId/bom/new";
      preLoaderRoute: typeof TeamProgramNumberRobotsRobotIdBomNewIndexRouteImport;
      parentRoute: typeof TeamProgramNumberRoute;
    };
  }
}

interface TeamProgramNumberRouteChildren {
  TeamProgramNumberIndexRoute: typeof TeamProgramNumberIndexRoute;
  TeamProgramNumberSettingsSeasonsRoute: typeof TeamProgramNumberSettingsSeasonsRoute;
  TeamProgramNumberCalendarIndexRoute: typeof TeamProgramNumberCalendarIndexRoute;
  TeamProgramNumberFabricationIndexRoute: typeof TeamProgramNumberFabricationIndexRoute;
  TeamProgramNumberFinanceIndexRoute: typeof TeamProgramNumberFinanceIndexRoute;
  TeamProgramNumberMarketingIndexRoute: typeof TeamProgramNumberMarketingIndexRoute;
  TeamProgramNumberMembersIndexRoute: typeof TeamProgramNumberMembersIndexRoute;
  TeamProgramNumberOperationsIndexRoute: typeof TeamProgramNumberOperationsIndexRoute;
  TeamProgramNumberOrdersIndexRoute: typeof TeamProgramNumberOrdersIndexRoute;
  TeamProgramNumberOutreachIndexRoute: typeof TeamProgramNumberOutreachIndexRoute;
  TeamProgramNumberPartsIndexRoute: typeof TeamProgramNumberPartsIndexRoute;
  TeamProgramNumberRobotsIndexRoute: typeof TeamProgramNumberRobotsIndexRoute;
  TeamProgramNumberSettingsIndexRoute: typeof TeamProgramNumberSettingsIndexRoute;
  TeamProgramNumberSoftwareIndexRoute: typeof TeamProgramNumberSoftwareIndexRoute;
  TeamProgramNumberSponsorsIndexRoute: typeof TeamProgramNumberSponsorsIndexRoute;
  TeamProgramNumberVendorsIndexRoute: typeof TeamProgramNumberVendorsIndexRoute;
  TeamProgramNumberOrdersOrderIdIndexRoute: typeof TeamProgramNumberOrdersOrderIdIndexRoute;
  TeamProgramNumberOrdersNewIndexRoute: typeof TeamProgramNumberOrdersNewIndexRoute;
  TeamProgramNumberPartsPartIdIndexRoute: typeof TeamProgramNumberPartsPartIdIndexRoute;
  TeamProgramNumberPartsNewIndexRoute: typeof TeamProgramNumberPartsNewIndexRoute;
  TeamProgramNumberRobotsRobotIdIndexRoute: typeof TeamProgramNumberRobotsRobotIdIndexRoute;
  TeamProgramNumberRobotsNewIndexRoute: typeof TeamProgramNumberRobotsNewIndexRoute;
  TeamProgramNumberVendorsVendorIdIndexRoute: typeof TeamProgramNumberVendorsVendorIdIndexRoute;
  TeamProgramNumberPartsPartIdEditIndexRoute: typeof TeamProgramNumberPartsPartIdEditIndexRoute;
  TeamProgramNumberRobotsRobotIdBomIndexRoute: typeof TeamProgramNumberRobotsRobotIdBomIndexRoute;
  TeamProgramNumberRobotsRobotIdBomNewIndexRoute: typeof TeamProgramNumberRobotsRobotIdBomNewIndexRoute;
}

const TeamProgramNumberRouteChildren: TeamProgramNumberRouteChildren = {
  TeamProgramNumberIndexRoute: TeamProgramNumberIndexRoute,
  TeamProgramNumberSettingsSeasonsRoute: TeamProgramNumberSettingsSeasonsRoute,
  TeamProgramNumberCalendarIndexRoute: TeamProgramNumberCalendarIndexRoute,
  TeamProgramNumberFabricationIndexRoute:
    TeamProgramNumberFabricationIndexRoute,
  TeamProgramNumberFinanceIndexRoute: TeamProgramNumberFinanceIndexRoute,
  TeamProgramNumberMarketingIndexRoute: TeamProgramNumberMarketingIndexRoute,
  TeamProgramNumberMembersIndexRoute: TeamProgramNumberMembersIndexRoute,
  TeamProgramNumberOperationsIndexRoute: TeamProgramNumberOperationsIndexRoute,
  TeamProgramNumberOrdersIndexRoute: TeamProgramNumberOrdersIndexRoute,
  TeamProgramNumberOutreachIndexRoute: TeamProgramNumberOutreachIndexRoute,
  TeamProgramNumberPartsIndexRoute: TeamProgramNumberPartsIndexRoute,
  TeamProgramNumberRobotsIndexRoute: TeamProgramNumberRobotsIndexRoute,
  TeamProgramNumberSettingsIndexRoute: TeamProgramNumberSettingsIndexRoute,
  TeamProgramNumberSoftwareIndexRoute: TeamProgramNumberSoftwareIndexRoute,
  TeamProgramNumberSponsorsIndexRoute: TeamProgramNumberSponsorsIndexRoute,
  TeamProgramNumberVendorsIndexRoute: TeamProgramNumberVendorsIndexRoute,
  TeamProgramNumberOrdersOrderIdIndexRoute:
    TeamProgramNumberOrdersOrderIdIndexRoute,
  TeamProgramNumberOrdersNewIndexRoute: TeamProgramNumberOrdersNewIndexRoute,
  TeamProgramNumberPartsPartIdIndexRoute:
    TeamProgramNumberPartsPartIdIndexRoute,
  TeamProgramNumberPartsNewIndexRoute: TeamProgramNumberPartsNewIndexRoute,
  TeamProgramNumberRobotsRobotIdIndexRoute:
    TeamProgramNumberRobotsRobotIdIndexRoute,
  TeamProgramNumberRobotsNewIndexRoute: TeamProgramNumberRobotsNewIndexRoute,
  TeamProgramNumberVendorsVendorIdIndexRoute:
    TeamProgramNumberVendorsVendorIdIndexRoute,
  TeamProgramNumberPartsPartIdEditIndexRoute:
    TeamProgramNumberPartsPartIdEditIndexRoute,
  TeamProgramNumberRobotsRobotIdBomIndexRoute:
    TeamProgramNumberRobotsRobotIdBomIndexRoute,
  TeamProgramNumberRobotsRobotIdBomNewIndexRoute:
    TeamProgramNumberRobotsRobotIdBomNewIndexRoute,
};

const TeamProgramNumberRouteWithChildren =
  TeamProgramNumberRoute._addFileChildren(TeamProgramNumberRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  VendorsRoute: VendorsRoute,
  TeamsJoinRoute: TeamsJoinRoute,
  TeamsNewRoute: TeamsNewRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  TeamProgramNumberRoute: TeamProgramNumberRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
